#!/usr/bin/env bash

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Enable firewall and allow necessary services
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'

# Create a simple HTML file
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Configure Nginx to add the custom header with the hostname
custom_header="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s|server_name _;|$custom_header|" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
