#!/usr/bin/env bash

# Update package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 6160-web-01 54.86.211.123:80 check
    server 6160-web-02 100.27.210.129:80 check
EOL

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Ensure the init script is available and executable
sudo ln -s /usr/lib/systemd/system/haproxy.service /etc/init.d/haproxy
sudo chmod +x /etc/init.d/haproxy

# Confirm HAProxy is running
sudo systemctl status haproxy

