#!/usr/bin/env bash
# SetUp Process for Nginx on a server

apt-get -y update
apt-get -y install nginx
ufw enable
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /tmp/correction/0230576279320925234434643821161266656684_5/2026/6160/web_server/output
service nginx restart
