#!/usr/bin/env bash
# script that install nginx and configure it to return custom 404 page not found error
nginx
server {
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
        return 404 "Ceci n'est pas une page";
    }
}
